// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Only the Prisma CLI (migrate, studio, etc.) reads this config — the running
  // app connects separately via its own adapter using DATABASE_URL (pooled),
  // see src/lib/prisma.ts. CLI commands use the unpooled URL since pooled
  // connections can't reliably hold the advisory lock migrations use.
  datasource: {
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
